version: "3"
services:
    shopware:
      image: dockware/dev:latest
      container_name: tester
      ports:
        - "80:80"
        - "3306:3306"
        - "22:22"
        - "8888:8888"
        - "9999:9999"
        - "9998:9998"
        - "443:443"
      volumes:
        - "db_volume:/var/lib/mysql"
        - "./custom/plugins:/var/www/html/custom/plugins"
      networks:
        - web
      environment:
        - XDEBUG_ENABLED=1
      
volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local
networks:
  web:
    external: false
